### ISSUE TITLE
Compton config

### ISSUE THREAD

**Issue by ApolloBian** [phuhl/.dotfiles#2]
Hi, I'd like to use your compton config. I noticed that you are using the kawase blur method with the xrender backend. How do you achieve that? The tryone144 branch claimed to only support glx backend.

**Comment by phuhl** [comment]
Hi, I think the value from the configuration might be overwritten by the command I use to start Compton. Take a look into this file:
system/launch_linux_desktop.sh

Hope that helps.

**Comment by ApolloBian** [comment]
Yes that helps. Thanks a lot!
